
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Expltextt imports to satisfy Flake8
from tkinter import Tk, Canvas, PhotoImage

# Obtenez le chemin absolu du répertoire contenant le script en cours d'exécution

def affiche_stat(text1, text2, text3, text4, text5, text6, text7):
    script_dir = Path(__file__).resolve().parent
    ASSETS_PATH =  script_dir / "assets" /"frame3"


    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)


    window = Tk()

    window.geometry("1440x818")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 818,
        width = 1440,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        720.0,
        409.0,
        image=image_image_1
    )

    canvas.create_text(
        238.0,
        61.0,
        anchor="nw",
        text="Analyse des résultats",
        fill="#FFFFFF",
        font=("DoppioOne Regular", 96 * -1)
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        719.0,
        259.0,
        image=image_image_2
    )

    canvas.create_text(
        462.0,
        233.0,
        anchor="nw",
        text="Interprétation des résultats",
        fill="#FFFFFF",
        font=("Nokora Regular", 40 * -1)
    )

    image_image_3 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    image_3 = canvas.create_image(
        1395.0,
        769.0,
        image=image_image_3
    )

    image_image_4 = PhotoImage(
        file=relative_to_assets("image_4.png"))
    image_4 = canvas.create_image(
        365.0,
        382.0,
        image=image_image_4
    )

    image_image_5 = PhotoImage(
        file=relative_to_assets("image_5.png"))
    image_5 = canvas.create_image(
        702.0,
        380.0,
        image=image_image_5
    )

    image_image_6 = PhotoImage(
        file=relative_to_assets("image_6.png"))
    image_6 = canvas.create_image(
        1039.0,
        376.0,
        image=image_image_6
    )

    canvas.create_rectangle(
        287.0,
        436.0,
        441.0,
        505.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        316.0,
        454.0,
        anchor="nw",
        text=text1,
        fill="#000000",
        font=("Nokora Regular", 18 * -1)
    )

    canvas.create_rectangle(
        626.0,
        436.0,
        780.0,
        505.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        655.0,
        454.0,
        anchor="nw",
        text=text2,
        fill="#000000",
        font=("Nokora Regular", 18 * -1)
    )

    canvas.create_rectangle(
        963.0,
        437.0,
        1117.0,
        506.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        992.0,
        455.0,
        anchor="nw",
        text=text3,
        fill="#000000",
        font=("Nokora Regular", 18 * -1)
    )

    image_image_7 = PhotoImage(
        file=relative_to_assets("image_7.png"))
    image_7 = canvas.create_image(
        214.0,
        592.0,
        image=image_image_7
    )

    image_image_8 = PhotoImage(
        file=relative_to_assets("image_8.png"))
    image_8 = canvas.create_image(
        551.0,
        590.0,
        image=image_image_8
    )

    image_image_9 = PhotoImage(
        file=relative_to_assets("image_9.png"))
    image_9 = canvas.create_image(
        888.0,
        586.0,
        image=image_image_9
    )

    canvas.create_rectangle(
        136.0,
        646.0,
        290.0,
        715.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        165.0,
        664.0,
        anchor="nw",
        text=text4,
        fill="#000000",
        font=("Nokora Regular", 18 * -1)
    )

    canvas.create_rectangle(
        475.0,
        646.0,
        629.0,
        715.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        504.0,
        664.0,
        anchor="nw",
        text=text5,
        fill="#000000",
        font=("Nokora Regular", 18 * -1)
    )

    canvas.create_rectangle(
        812.0,
        647.0,
        966.0,
        716.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        841.0,
        665.0,
        anchor="nw",
        text=text6,
        fill="#000000",
        font=("Nokora Regular", 18 * -1)
    )

    image_image_10 = PhotoImage(
        file=relative_to_assets("image_10.png"))
    image_10 = canvas.create_image(
        1225.0,
        586.0,
        image=image_image_10
    )

    canvas.create_rectangle(
        1149.0,
        647.0,
        1303.0,
        716.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        1178.0,
        665.0,
        anchor="nw",
        text=text7,
        fill="#000000",
        font=("Nokora Regular", 18 * -1)
    )
    window.resizable(False, False)
    window.mainloop()

