
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\paulg\Documents\GitHub\Tkinter-Designer\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x818")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 818,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    720.0,
    409.0,
    image=image_image_1
)

canvas.create_text(
    238.0,
    61.0,
    anchor="nw",
    text="Analyse des résultats",
    fill="#FFFFFF",
    font=("DoppioOne Regular", 96 * -1)
)

canvas.create_rectangle(
    120.0,
    355.0,
    1321.0,
    793.0,
    fill="#D9D9D9",
    outline="")

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    719.0,
    259.0,
    image=image_image_2
)

canvas.create_text(
    462.0,
    233.0,
    anchor="nw",
    text="Interprétation des résultats",
    fill="#FFFFFF",
    font=("Nokora Regular", 40 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1395.0,
    769.0,
    image=image_image_3
)
window.iconphoto(True, image_image_3)
window.resizable(False, False)
window.mainloop()
